[doc] 增加TX2文档和benchmark测试
PaddlePaddle/PaddleDetection pull request #1650
Opened 2020-11-03 13:49 UTC by liuhuiCNN

增加TX2文档和benchmark测试

2020-11-04 13:02 UTC, wangxinxin08 requested changes

2020-11-04 13:02 UTC, wangxinxin08 commented on deploy/cpp/build.sh
>  # 是否使用GPU(即是否使用 CUDA)
deploy/cpp/scripts/build.sh的目录不要改动，保持原路径

2020-11-04 13:02 UTC, wangxinxin08 commented on deploy/cpp/build.sh
> -rm -rf build
这一部分内容不要删去

2020-11-04 13:02 UTC, wangxinxin08 commented on deploy/cpp/docs/linux_build.md
> -rm -rf build
同上

2020-11-04 13:02 UTC, wangxinxin08 commented on deploy/cpp/docs/linux_build.md
> - sh ./scripts/build.sh
同上

2020-11-04 13:02 UTC, wangxinxin08 commented on deploy/cpp/docs/linux_build.md
> -./build/main --model_dir=/root/projects/models/yolov3_darknet --image_path=/root/projects/images/test.jpeg
同上

2020-11-04 13:02 UTC, wangxinxin08 commented on deploy/cpp/docs/linux_build.md
> -./build/main --model_dir=/root/projects/models/yolov3_darknet --video_path=/root/projects/images/test.mp4 --use_gpu=1
同上

2020-11-04 13:04 UTC, liuhuiCNN commented on deploy/cpp/docs/linux_build.md
> -rm -rf build
done

2020-11-04 13:04 UTC, liuhuiCNN commented on deploy/cpp/build.sh
>  # 是否使用GPU(即是否使用 CUDA)
done thanks.

2020-11-04 13:04 UTC, liuhuiCNN commented on deploy/cpp/build.sh
> -rm -rf build
done thanks.

2020-11-04 13:04 UTC, liuhuiCNN commented on deploy/cpp/docs/linux_build.md
> -rm -rf build
done thanks.

2020-11-04 13:04 UTC, liuhuiCNN commented on deploy/cpp/docs/linux_build.md
> -./build/main --model_dir=/root/projects/models/yolov3_darknet --video_path=/root/projects/images/test.mp4 --use_gpu=1
done thanks.

2020-11-04 13:04 UTC, liuhuiCNN commented on deploy/cpp/docs/linux_build.md
> -./build/main --model_dir=/root/projects/models/yolov3_darknet --image_path=/root/projects/images/test.jpeg
done thanks.

2020-11-05 04:14 UTC, wangxinxin08 commented on deploy/cpp/scripts/build.sh
> +# 或者根据平台下载对应平台上opencv编译好的文件并设置路径
建议删掉这一部分内容，因为已经自动下载了

2020-11-05 05:02 UTC, qingqing01 commented on deploy/cpp/docs/TX2_build.md
> +测试环境为：硬件: TX2，JetPack版本: 4.3, Paddle预测库: 1.8.4，CUDA: 10.0, CUDNN: 7.5.
也说下TensorRT的版本号

2020-11-05 05:03 UTC, qingqing01 commented on deploy/cpp/docs/TX2_build.md
> +|模型 | 输入| AnalysisPredictor(ms) |
FP32精度也说下，FP16后续可以加下

2020-11-05 06:01 UTC, liuhuiCNN commented on deploy/cpp/docs/TX2_build.md
> +测试环境为：硬件: TX2，JetPack版本: 4.3, Paddle预测库: 1.8.4，CUDA: 10.0, CUDNN: 7.5.
done

2020-11-05 06:05 UTC, liuhuiCNN commented on deploy/cpp/docs/TX2_build.md
> +|模型 | 输入| AnalysisPredictor(ms) |
FP32 现在是指定输入640x640测试的，跟fluid的不一样。等后面用2.0-beta版本的预测库，测试变长输入结果后再补充吧？

2020-11-05 08:50 UTC, wangxinxin08 commented on deploy/cpp/docs/linux_build.md
> +# OPENCV_DIR 的路径
和build.sh里面保持一致

2020-11-05 11:37 UTC, liuhuiCNN commented on deploy/cpp/docs/linux_build.md
> +# OPENCV_DIR 的路径
done, thanks

2020-11-05 13:01 UTC, wangxinxin08 approved these changes

2020-11-05 17:12 UTC, merged