fix bug
PaddlePaddle/PaddleDetection pull request #1792
Opened 2020-12-01 13:14 UTC by liuhuiCNN

（1）eval 结束后随机挂问题
（2）windows编译失败问题

2020-12-02 03:16 UTC, qingqing01 requested changes
也请正确给出标题描述

2020-12-02 03:16 UTC, qingqing01 commented on configs/yolov3_mobilenet_v1_roadsign.yml
> +  batch_size: 1
快速开始的batch-size不要随意的改动，改动之后，精度咋样，lr是否调整等

2020-12-02 09:13 UTC, liuhuiCNN commented on configs/yolov3_mobilenet_v1_roadsign.yml
> +  batch_size: 1
这是eval的batch_size，不影响训练。

2020-12-03 02:28 UTC, qingqing01 approved these changes

2020-12-06 09:00 UTC, liuhuiCNN commented
the ci of github is always failed, so move to #1822

2020-12-06 11:02 UTC, closed without merging