[dev] fix s2anet install and train on CPU
PaddlePaddle/PaddleDetection pull request #2807
Opened 2021-04-28 13:52 UTC by liuhuiCNN

(1) fix s2anet install and train on CPU

2021-04-29 04:47 UTC, yghstill commented on ppdet/modeling/bbox_utils.py
> +    bboxes = bboxes.numpy()
为什么转成numpy处理，tensor 切片赋值等功能paddle均已支持。

2021-04-29 06:24 UTC, liuhuiCNN commented on ppdet/modeling/bbox_utils.py
> +    bboxes = bboxes.numpy()
paddle tensor 不支持bool类型的下标索引。后来通过别的方式绕过去了，代码在后面动转静的commit中。

2021-05-07 05:26 UTC, qingqing01 requested changes

2021-05-07 05:26 UTC, qingqing01 commented on ppdet/modeling/bbox_utils.py
> +def rect2rbox_pd(bboxes):
上面rect2rbox是paddle tensor和np混合。这个函数是numpy实现。 这两个区别是啥？

2021-05-07 05:26 UTC, qingqing01 commented on ppdet/modeling/heads/s2anet_head.py
> +        shift_y = paddle.fluid.layers.range(0, feat_h, 1, 'int32') * stride
paddle.range

2021-05-07 05:26 UTC, qingqing01 commented on ppdet/modeling/heads/s2anet_head.py
> +        # for debug 0426
del this line

2021-05-07 05:26 UTC, qingqing01 commented on ppdet/modeling/heads/s2anet_head.py
> +        feat_labels = paddle.to_tensor(feat_labels)
feat_labels前面都是numpy吗?

2021-05-07 05:26 UTC, qingqing01 commented on ppdet/modeling/heads/s2anet_head.py
> +        feat_labels_one_hot = paddle.nn.functional.one_hot(
import paddle.nn.functional as F

F.one_hot

2021-05-07 05:26 UTC, qingqing01 commented on ppdet/modeling/bbox_utils.py
> +def rect2rbox_pd(bboxes):
建议把 rbbox相关的独立一个文件

2021-05-12 07:30 UTC, closed without merging