[dev] s2anet fix export and deploy
PaddlePaddle/PaddleDetection pull request #2919
Opened 2021-05-10 04:10 UTC by liuhuiCNN

(1) fix export and deploy

2021-05-10 05:13 UTC, qingqing01 commented on ppdet/modeling/heads/s2anet_head.py
> +        feat_labels_one_hot = paddle.nn.functional.one_hot(
最开始有import:

https://github.com/PaddlePaddle/PaddleDetection/blob/7aff0dcee04bfbaf15d3f1cf79ed25484eeac381/ppdet/modeling/heads/s2anet_head.py#L17

这里调用可以考虑简化，另外一个PR review时已经提过~

2021-05-10 05:13 UTC, qingqing01 commented on ppdet/modeling/heads/s2anet_head.py
> +        odm_cls_score, odm_bbox_pred = s2anet_head_out
接口参数展开，更加明确~~

2021-05-10 05:13 UTC, qingqing01 commented on ppdet/modeling/post_process.py
> +        #self.fake_bbox_num = paddle.ones([1], dtype='int32')
remove un-used code

2021-05-10 05:13 UTC, qingqing01 commented on ppdet/modeling/post_process.py
> +        pred_ploys0 = pd_rbox2poly(pred_bboxes)
pd_rbox2poly 前缀加 pd_的目的？

2021-05-10 05:13 UTC, qingqing01 commented on ppdet/modeling/post_process.py
> +            print('create fake data')
remove debug code

2021-05-10 05:13 UTC, qingqing01 commented on ppdet/modeling/post_process.py
> +            bbox_num = self.fake_bbox_num
这里为啥移动到init里创建fake数据呢？

2021-05-10 05:18 UTC, qingqing01 commented on configs/dota/_base_/s2anet_reader.yml
> +  - PadBatch: {pad_to_stride: 32, pad_gt: false}
这里为什么和Train/Eval不一致？

2021-05-10 05:18 UTC, qingqing01 requested changes

2021-05-10 05:18 UTC, qingqing01 commented on deploy/python/infer.py
> +        config.switch_ir_optim(False)
remove this line

2021-05-10 05:36 UTC, liuhuiCNN commented on deploy/python/infer.py
> +        config.switch_ir_optim(False)
done

2021-05-10 05:38 UTC, liuhuiCNN commented on ppdet/modeling/post_process.py
> +            bbox_num = self.fake_bbox_num
留杰的建议，将to_tensor改成成员变量比较好。

2021-05-10 05:38 UTC, liuhuiCNN commented on ppdet/modeling/post_process.py
> +            print('create fake data')
done

2021-05-10 05:42 UTC, liuhuiCNN commented on ppdet/modeling/post_process.py
> +        pred_ploys0 = pd_rbox2poly(pred_bboxes)
这个函数是paddle实现的，已经改成不加pd_前缀。

2021-05-10 05:44 UTC, liuhuiCNN commented on ppdet/modeling/post_process.py
> +        #self.fake_bbox_num = paddle.ones([1], dtype='int32')
done

2021-05-10 05:53 UTC, yghstill commented on ppdet/modeling/post_process.py
> +        self.fake_pred_cls_score_bbox = paddle.to_tensor(
加入fake data后网络中会增加condition block，对预测部署不利，现在网络输出支持box为[]，应该去掉fake data，目前其他模型在post_process中都已经去除fake data，建议修正。

2021-05-10 10:05 UTC, liuhuiCNN commented on configs/dota/_base_/s2anet_reader.yml
> +  - PadBatch: {pad_to_stride: 32, pad_gt: false}
统一成PadBatch

2021-05-10 10:07 UTC, liuhuiCNN commented on ppdet/modeling/heads/s2anet_head.py
> +        odm_cls_score, odm_bbox_pred = s2anet_head_out
返回参数比较多，这些参数是具有逻辑意义的，感觉这样也可以。

2021-05-10 10:10 UTC, liuhuiCNN commented on ppdet/modeling/post_process.py
> +        self.fake_pred_cls_score_bbox = paddle.to_tensor(
现在fake data已经测试通过了，去除fake data作为TODO下个PR再优化吧。

2021-05-11 02:51 UTC, qingqing01 commented on ppdet/data/source/category.py
> +def get_categories(metric_type, anno_file=None, arch=None):
https://github.com/PaddlePaddle/PaddleDetection/blob/8336430146c460d2777b89df7fbffc3e9a20fe1c/ppdet/data/source/category.py#L29

最新的代码已经改过了，更新下代码到最新

2021-05-11 05:44 UTC, liuhuiCNN commented on ppdet/data/source/category.py
> +def get_categories(metric_type, anno_file=None, arch=None):
done

2021-05-11 07:06 UTC, yghstill commented on deploy/cpp/src/object_detector.cc
> +            cv::Point pt1 = cv::Point(results[i].rect[(k*2)%8], results[i].rect[(k*2+1)%8]);
c++ code style 每行不超过80字符

2021-05-11 07:06 UTC, yghstill commented on ppdet/modeling/heads/s2anet_head.py
> +        # feat_h, feat_w = featmap_size
这行注释应删除

2021-05-11 07:06 UTC, yghstill commented on ppdet/modeling/heads/s2anet_head.py
> +        :param means:
补全注释内容

2021-05-11 07:06 UTC, yghstill commented on ppdet/modeling/heads/s2anet_head.py
> +            bbox_preds: [N,H,W,5]
same as above

2021-05-11 07:14 UTC, liuhuiCNN commented on deploy/cpp/src/object_detector.cc
> +            cv::Point pt1 = cv::Point(results[i].rect[(k*2)%8], results[i].rect[(k*2+1)%8]);
done

2021-05-11 07:17 UTC, liuhuiCNN commented on ppdet/modeling/heads/s2anet_head.py
> +        :param means:
done

2021-05-11 07:17 UTC, liuhuiCNN commented on ppdet/modeling/heads/s2anet_head.py
> +        # feat_h, feat_w = featmap_size
done

2021-05-11 07:21 UTC, liuhuiCNN commented on ppdet/modeling/heads/s2anet_head.py
> +            bbox_preds: [N,H,W,5]
done

2021-05-11 13:14 UTC, qingqing01 submitted a review, later dismissed

2021-05-12 05:12 UTC, yghstill approved these changes
LGTM for deploy

2021-05-12 05:15 UTC, qingqing01 approved these changes

2021-05-12 05:29 UTC, merged