[cherry-pick]fix video infer
PaddlePaddle/PaddleDetection pull request #5919
Opened 2022-05-10 06:44 UTC by wangxinxin08

cherry-pick https://github.com/PaddlePaddle/PaddleDetection/pull/5918 to release/2.4

2022-05-10 07:26 UTC, lazyn1997 commented
建议把这个转换放置到preprocess中，可以避免两次转换，同时在阅读代码时也更加便于理解，修改如下图所示
![image](https://user-images.githubusercontent.com/34644177/167572686-619fee52-944a-4eb3-bcb3-e3f9e1cfbba3.png)

2022-05-10 07:27 UTC, lazyn1997 requested changes
建议把这个转换放置到preprocess中，可以避免两次转换，同时在阅读代码时也更加便于理解

2022-05-10 11:21 UTC, wangxinxin08 commented
> 建议把这个转换放置到preprocess中，可以避免两次转换，同时在阅读代码时也更加便于理解

你可以仿照我这种方式，提两个PR分别到develop和release/2.4，另外，可以考虑下入锅preprocess的输入已经是一个RGB图像的处理，之后我们发版的时候会把你添加到contributer里面

2022-05-10 12:18 UTC, lazyn1997 commented
我已经修改并提交了，不过没有考虑preprocess的输入已经是一个RGB图像的情况，因为目前预测图片和视频都是用cv2读入的，没有RGB图像的情况

2022-05-10 12:26 UTC, wangxinxin08 commented
> 我已经修改并提交了，不过没有考虑preprocess的输入已经是一个RGB图像的情况，因为目前预测图片和视频都是用cv2读入的，没有RGB图像的情况

1. 可以考虑下这种情况，因为模型经常会被串联起来使用，比如检测+关键点，这时一般只会读一次图片，先进入检测后进入关键点，关键点模型的输入就是RGB的模式
2. cv2.VideoWriter应该是需要传入BGR的图像，所以这块怎么处理也可以考虑下
你可以考虑下上面两个问题，修改下PR，我来帮你review

2022-05-10 12:43 UTC, lazyn1997 commented
1.cv2.VideoWriter这里不会有问题，我已经测试过了，因为读取视频帧时为BGR图像，然后传入predict_image中进行预测，在此内部进行颜色空间的转换，因此传入visualize_box_mask的图像依然为BGR图像，
![image](https://user-images.githubusercontent.com/34644177/167629359-29ddfcdc-9957-4155-b2c6-391f02900b1b.png)
而visualize_box_mask也没有对数组类型进行颜色空间的转换，那么最终writer.write写入阶段的同样为BGR的图像
![image](https://user-images.githubusercontent.com/34644177/167629902-cb3cbcd7-dbcb-43b9-ab44-e1dcdbc2cf26.png)
也就是说在视频预测时，只是在predict_image的preprocess阶段进行了颜色转换，其他部分自始至终一直为BGR的图像。
2.关键点检测模型我没有用过，我先去看一下

2022-05-11 02:46 UTC, wangxinxin08 commented
> 2.关键点检测模型我没有用过，我先去看一下

2022-05-11 03:12 UTC, lazyn1997 commented
感谢你耐心的回复，刚开始的修改确实考虑不周，没有想到其他模型的兼容性

2022-05-11 07:23 UTC, wangxinxin08 commented
> 感谢你耐心的回复，刚开始的修改确实考虑不周，没有想到其他模型的兼容性，还是在infer的predict_video部分修改吧，我重新提交了PR

感谢你的贡献，我刚才突然想到，deploy/python目录下面还有很多infer文件，可以麻烦你都修改下吗？

2022-05-11 08:46 UTC, lazyn1997 commented
我看了deplo/python中所有infer文件，在develop和release/2.4分支下，对比如下：
1. action_infer.py中未找到infer video相关内容
2. attr_infer.py中未找到infer video相关内容
3. det_keypoint_unite_infer.py中找到infer video相关内容，现有代码已经进行了convert，截图如下：
![image](https://user-images.githubusercontent.com/34644177/167800380-91f0efa6-d17a-423d-b087-d26dc03880e0.png)
4. keypoint_infer.py未进行convert，已进行修改
![image](https://user-images.githubusercontent.com/34644177/167802433-0050f744-9c47-4c9d-9c8c-b03e356837ca.png)
5. mot_jde_infer.py未进行convert，已进行修改
![image](https://user-images.githubusercontent.com/34644177/167803741-691c66d8-e013-4b0e-b693-6c573a94e0db.png)
6. mot_keypoint_unite_infer.py未进行convert，且两次用到frame，参考det_keypoint_unite_infer.py进行修改
![image](https://user-images.githubusercontent.com/34644177/167805361-6a1dfc6e-e2c3-4672-b0b5-49f626671380.png)
7. mot_sde_infer.py未进行convert，已进行修改
![image](https://user-images.githubusercontent.com/34644177/167806273-449d4535-f7f1-48c5-8a87-4d1553ca6df9.png)

2022-05-11 11:27 UTC, lazyn1997 commented
check出错了，不知道什么问题

2022-05-11 12:01 UTC, wangxinxin08 commented
> check出错了，不知道什么问题

我在看

2022-05-11 13:12 UTC, lazyn1997 commented
> > check出错了，不知道什么问题
> 
> 我在看， 这个PR：#5930 可以合并下最新的分支, upstream为https://github.com/PaddlePaddle/PaddleDetection 这里会把你的改动rebase到最新的分支，具体命令为
> 
> ```shell
> git fetch upstream
> git pull upstream release/2.4 --rebase
> ```

我执行后提示下图这样，然后按照第二张图进行操作
![image](https://user-images.githubusercontent.com/34644177/167857887-94f4030a-6de9-44cf-88dd-7add2e2f40ce.png)
![image](https://user-images.githubusercontent.com/34644177/167858015-29278f30-928a-4c38-a618-e47f4a2e539d.png)
现在PR那里多了很多commit，应该是这样吗？
![image](https://user-images.githubusercontent.com/34644177/167858140-233dd8f4-7c47-4ce0-bb17-2cd65fd0b83f.png)

2022-05-11 14:50 UTC, lazyn1997 commented
develop分支的通过了(#5931)

2022-05-13 03:03 UTC, lazyn1997 commented
新提交的release/2.4分支还是由于同样的错误check失败了，对比发现应该是solov2出错了，但不知道什么错
![image](https://user-images.githubusercontent.com/34644177/168203060-258deef1-848a-4ea3-94e9-7f8da8a3c5ae.png)

2022-05-13 12:18 UTC, lazyn1997 commented
我重新提交了一个，check通过了，麻烦帮忙review一下(#5973)

2022-05-17 07:33 UTC, closed without merging