[论文复现营] add QueryInst
PaddlePaddle/PaddleDetection pull request #7585
Opened 2023-01-03 08:45 UTC by ucsk

Notes:
- The modification of `ppdet/data/transform/operators.py` is the same as that of [SparseInst](https://github.com/PaddlePaddle/PaddleDetection/pull/7357) PR.
- 3x & num_proposals=300 is currently training.

2023-02-02 06:46 UTC, ghostxsl requested changes

2023-02-02 06:46 UTC, ghostxsl commented on ppdet/data/transform/operators.py
> +        del (sample['gt_poly'])
不要删除sample中的gt_poly，后续op可能还会用到

2023-02-02 06:46 UTC, ghostxsl commented on ppdet/data/transform/operators.py
> +        h = random.randint(
这里保持原来的写法会对你的模型不适用嘛？

2023-02-02 13:34 UTC, ucsk commented on ppdet/data/transform/operators.py
> +        del (sample['gt_poly'])
新增关于生成gt_segm后是否将gt_poly删除的开关，默认不删除。

2023-02-02 13:35 UTC, ucsk commented on ppdet/data/transform/operators.py
> +        h = random.randint(
已保持原来的写法。

2023-02-03 02:47 UTC, jerrywgz commented on configs/queryinst/_base_/queryinst_reader.yml
> +  - Gt2SparseTarget: {}
Eval和Test阶段不需要生成target吧？

2023-02-03 02:47 UTC, jerrywgz commented on ppdet/modeling/architectures/queryinst.py
> +# Copyright (c) 2022 PaddlePaddle Authors. All Rights Reserved.
2022->2023 其他新增文件同

2023-02-03 07:33 UTC, ucsk commented on ppdet/modeling/architectures/queryinst.py
> +# Copyright (c) 2022 PaddlePaddle Authors. All Rights Reserved.
已完成。

2023-02-03 07:38 UTC, ucsk commented on configs/queryinst/_base_/queryinst_reader.yml
> +  - Gt2SparseTarget: {}
`proposal_bboxes`是一个batch中各个图像的相对坐标，所以预测阶段也是需要图像的具体尺寸。

2023-02-06 07:03 UTC, ghostxsl approved these changes

2023-02-07 03:29 UTC, lyuwenyu approved these changes

2023-02-07 03:33 UTC, merged