keypoint petr
PaddlePaddle/PaddleDetection pull request #7774
Opened 2023-02-16 03:48 UTC by zhiboniu

keypoint petr

2023-02-16 07:28 UTC, ghostxsl requested changes

2023-02-16 07:28 UTC, ghostxsl commented on ppdet/data/transform/operators.py
> +                iou = self._gtcropiou_matrix(
_iou_matrix和_gtcropiou_matrix这两个函数的行为不一致，这里不能直接替换

2023-02-16 07:28 UTC, ghostxsl commented on ppdet/data/transform/operators.py
> +                iou = self._gtcropiou_matrix(
同上

2023-02-16 07:28 UTC, ghostxsl commented on ppdet/modeling/transformers/deformable_transformer.py
> +                key,
加这个key的意义在哪里？函数里并没有使用。如果是关键点模型需要使用的话，没必要强行复用这里的函数，可以在关键点模型里重写一个函数继承一下，单独改写这个forward函数。你这里的改动让检测这边不好兼容，关键点和检测的架构不一样，没必要强行耦合在一起，这对后续复现其他模型增加了难度

2023-02-16 07:28 UTC, ghostxsl commented on ppdet/modeling/transformers/detr_transformer.py
> +                 attn=None,
同上

2023-02-16 07:28 UTC, ghostxsl commented on ppdet/modeling/transformers/detr_transformer.py
> +        self.embed_dims = encoder_layer.embed_dims
同上

2023-02-16 07:28 UTC, ghostxsl commented on ppdet/modeling/transformers/dino_transformer.py
> +            self.with_pos_embed(src, query_pos_embed), None, src,
同上

2023-02-16 07:37 UTC, nemonameless commented on configs/keypoint/petr/pert_resnet50_16x2_coco.yml
> +pretrain_weights: Trunc_epoch_1_0.pdparams
上传预训练，和更新modelzoo

2023-02-16 07:52 UTC, zhiboniu commented on ppdet/data/transform/operators.py
> +                iou = self._gtcropiou_matrix(
_iou_matrix计算的是框重叠部分与crop和gt框总和的比例，如果crop面积远大于gt面积，则该值始终很小，例如一直小于0.1。所以这里的原意我理解是对gt保留比例的过滤，应该使用框重叠部分与gt框的比例来计算。因此做了如上修改，请再考虑确认一下吧

2023-02-16 07:52 UTC, zhiboniu commented on ppdet/data/transform/operators.py
> +                iou = self._gtcropiou_matrix(
同上

2023-02-16 07:55 UTC, zhiboniu commented on ppdet/modeling/transformers/deformable_transformer.py
> +                key,
加这个key是为了在petr中模块式堆叠搭建网络时，各模块函数输入输出格式保持一致 。我看现在其他地方的调用都是直接写在代码里的好改一些，目前的使用我已经修改了，可以看看修改是否有问题。

2023-02-16 08:09 UTC, zhiboniu commented on configs/keypoint/petr/pert_resnet50_16x2_coco.yml
> +pretrain_weights: Trunc_epoch_1_0.pdparams
这里模型结构也是尝试在配置文件中模块式搭建网络的尝试，原来的模型结构分开各部分写需要在类的实现里做修改，灵活性低一些。这个模型先这样吧。预训练和modelzoo可以后面再改，先看看代码是否有问题。

2023-02-17 03:55 UTC, lyuwenyu approved these changes

2023-02-17 03:58 UTC, lyuwenyu commented on .gitignore
> +ppdet/modeling/transformers/ext_op/dist/
这个要不改成  *build/  *egg-info/  *dist/通配符的形式 ？

2023-02-17 04:02 UTC, lyuwenyu commented on configs/keypoint/petr/pert_resnet50_16x2_coco.yml
> +pretrain_weights: Trunc_epoch_1_0.pdparams
还有这个链接是不是不对

2023-02-17 04:33 UTC, ghostxsl submitted a review, later dismissed

2023-02-17 05:44 UTC, zhiboniu commented on .gitignore
> +ppdet/modeling/transformers/ext_op/dist/
可以的，但是如果没有其他地方有类似的目录，那现在这种就也一样的

2023-02-17 05:44 UTC, zhiboniu commented on configs/keypoint/petr/pert_resnet50_16x2_coco.yml
> +pretrain_weights: Trunc_epoch_1_0.pdparams
嗯，预训练模型晚点再修改，还没准备好，先看代码吧

2023-02-17 06:16 UTC, lyuwenyu approved these changes, later dismissed

2023-02-17 07:14 UTC, zhiboniu commented on .gitignore
> +ppdet/modeling/transformers/ext_op/dist/
done

2023-02-17 07:14 UTC, zhiboniu commented on configs/keypoint/petr/pert_resnet50_16x2_coco.yml
> +pretrain_weights: Trunc_epoch_1_0.pdparams
done,已修改

2023-02-21 09:33 UTC, jerrywgz commented on ppdet/data/source/__init__.py
> +from .petr_coco import PETRCocoDataset
dataset有办法和关键点的dataset兼容吗，这个有点太定制了

2023-02-21 11:24 UTC, zhiboniu commented on ppdet/data/source/__init__.py
> +from .petr_coco import PETRCocoDataset
这个训练文件是好几个json都需要一起加载，实现比较复杂，而且内容格式也有些差别，感觉还是先独立开吧

2023-02-22 03:03 UTC, zhiboniu commented on ppdet/data/source/__init__.py
> +from .petr_coco import PETRCocoDataset
done

2023-02-22 03:05 UTC, jerrywgz submitted a review, later dismissed

2023-02-22 03:09 UTC, lyuwenyu approved these changes, later dismissed

2023-02-22 10:45 UTC, jerrywgz approved these changes

2023-02-22 11:04 UTC, lyuwenyu approved these changes

2023-02-22 11:07 UTC, merged