[Feature]Complete the ACT for detection models.
PaddlePaddle/PaddleDetection pull request #8747
Opened 2023-12-10 08:34 UTC by ranchongzhi

Complete the act based on https://github.com/PaddlePaddle/PaddleDetection/pull/8627

2023-12-13 11:15 UTC, shiyutang commented
@ranchongzhi  这个是否ready可以测试呢？

2023-12-13 11:20 UTC, ranchongzhi commented
> @ranchongzhi 这个是否ready可以测试呢？

可以的

2023-12-27 12:14 UTC, shiyutang requested changes
可以在readme中增加[deploy/auto_compression/test_pass.sh](https://github.com/PaddlePaddle/PaddleDetection/pull/8747/files#diff-bca22d18446969868e5b546babd7216da05ef65bf95a09cf53e39240dcc6c594)的说明，怎么用于自动化寻找有问题的pass。

2023-12-27 12:14 UTC, shiyutang commented on deploy/auto_compression/README.md
> -- 表格中的性能在Tesla T4的GPU环境下测试，并且开启TensorRT，batch_size=1。
保留之前的其他量化模型效果。

2023-12-27 12:14 UTC, shiyutang commented on deploy/auto_compression/README.md
> -- PP-YOLOE-SOD 的指标在VisDrone-DET数据集切图后的COCO格式[数据集](https://bj.bcebos.com/v1/paddledet/data/smalldet/visdrone_sliced.zip)中评测得到，IoU=0.5:0.95。定义文件[ppyoloe_crn_l_80e_sliced_visdrone_640_025.yml](../../con
PP-YOLOE下可以放两个表格，尽量不影响原有的信息表达。

2023-12-30 09:50 UTC, ranchongzhi commented on deploy/auto_compression/README.md
> -- 表格中的性能在Tesla T4的GPU环境下测试，并且开启TensorRT，batch_size=1。
done

2023-12-30 09:50 UTC, ranchongzhi commented on deploy/auto_compression/README.md
> -- PP-YOLOE-SOD 的指标在VisDrone-DET数据集切图后的COCO格式[数据集](https://bj.bcebos.com/v1/paddledet/data/smalldet/visdrone_sliced.zip)中评测得到，IoU=0.5:0.95。定义文件[ppyoloe_crn_l_80e_sliced_visdrone_640_025.yml](../../con
done

2024-01-02 02:47 UTC, shiyutang requested changes

2024-01-02 02:47 UTC, shiyutang commented on deploy/auto_compression/README.md
> -| PicoDet-S-NPU |  量化训练 | 29.7  |   -  |   -   |  -  |  [config](https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/full_quantization/detection/configs/picodet_s_qat_dis.yaml) | [Model](htt
这一部分也不要删除吧，NPU的可以单独有一个表格

2024-01-02 02:47 UTC, shiyutang commented on deploy/auto_compression/test_det.py
> +        #     return
不需要的代码需要删除

2024-01-03 11:05 UTC, ranchongzhi commented on deploy/auto_compression/test_det.py
> +        #     return
done

2024-01-03 11:05 UTC, ranchongzhi commented on deploy/auto_compression/README.md
> -| PicoDet-S-NPU |  量化训练 | 29.7  |   -  |   -   |  -  |  [config](https://github.com/PaddlePaddle/PaddleSlim/tree/develop/demo/full_quantization/detection/configs/picodet_s_qat_dis.yaml) | [Model](htt
我是看到结果不是很全就删除了，已恢复

2024-01-04 03:04 UTC, shiyutang approved these changes
LGTM

2024-01-04 03:16 UTC, lyuwenyu approved these changes

2024-01-04 03:54 UTC, merged